jenkins:
  build: .
  volumes:
    - ./data:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
    - ./config/executors.groovy:/usr/share/jenkins/ref/init.groovy.d/executors.groovy
  ports:
    - 8080:8080
    - 50000:50000
